version: '3.8'

networks:
  default:
    name: voi-js-client-network
    driver: bridge

services:
  voi-js-client:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: voi-js-client-container
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16g
    ports:
      - "443:8080"
    volumes:
      - ../:/home/user/voi-js-client
      - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
      - ${HOME}/.cursor-server:/home/user/.cursor-server
      - ${HOME}/.cache:/home/user/.cache